### ISSUE TITLE
[Bug Report] Corruption occurs when upgrading vscode through package manager in some Linux distributions

### ISSUE THREAD

**Issue by ZhenyaGoroh** [shalldie/vscode-background#487] opened 2024-10-31 13:09 UTC
## Summary | 概述

The extension ruins the whole vscode 

### Versions
![image](https://github.com/user-attachments/assets/fd42d2e3-bdaa-47b1-8f64-d23800ed78c0)

- Linux, Ubuntu:
- vscode: 1.95

**Comment by comradez** [comment] 2024-10-31 22:00
It seems to disrupt all the text in the extension section.

**Comment by Zylsjsp** [comment] 2024-11-01 01:08
Could reproduce in 1.95.1

**Comment by shalldie** [comment] 2024-11-01 03:00
@ZhenyaGoroh 
Try this two ways to make a fix: [how-to-uninstall](https://github.com/shalldie/vscode-background/blob/master/docs/common-issues.md#how-to-uninstall) ,  [vscode-crashes](https://github.com/shalldie/vscode-background/blob/master/docs/common-issues.md#vscode-crashes-306)

@comradez @Zylsjsp 
Have you also encountered it and is it also on Ubuntu?

**Comment by EmmetZ** [comment] 2024-11-01 04:42
same problem on fedora 40

**Comment by shalldie** [comment] 2024-11-01 05:18
OK, I found a machine and will investigate the cause today

**Comment by Zylsjsp** [comment] 2024-11-01 05:24
@shalldie I'm on Archlinux, using [AUR package](https://aur.archlinux.org/packages/visual-studio-code-bin). The issue should be reproduced on any linux installation.
I'll try reinstalling the plugin to see if the issue also reproduces on Mac.

**Comment by Zylsjsp** [comment] 2024-11-01 05:42
On a new Mac universal installation v1.95.1 it's OK.

**Comment by shalldie** [comment] 2024-11-02 08:26
### Tested, works fine.

-  `Ubuntu 24.04.1 LTS`, I've tested it in `vscode 1.95.1` which installed by `.deb`.
- `Ubuntu 24.04.1 LTS`, also works fine with `vscode 1.95.0`, #485 

### Known issues

- ArchLinux with `vscode of binary version` is not supported. #408 
    - Seems your case. @Zylsjsp 
- Installed by `Snap` is not supported. #382
    - Error: (Linux) snap: read-only file system
    - Snap use [SquashFS](https://en.wikipedia.org/wiki/SquashFS) to storage packages. It's a compressed readonly file system. Packages installed via snap are immutable.

---

The above are some of the issues I have summarized, which will be added to the [Common Issue](https://github.com/shalldie/vscode-background/blob/master/docs/common-issues.md).
There are too many Linux distributions for me to test one by one. I hope everyone can give some suggestions when they have time.

**Comment by ZhangYaoan** [comment] 2024-11-03 01:51
I have the same issue on VSCodium 1.95.1, Fedora 41 (not binary version).

By the way, it's not just not working, but break all strings in VSCode (like this)
![截图 2024-11-03 09-48-17](https://github.com/user-attachments/assets/061a2480-57b3-436b-92f4-bdf48916ad9f)

**Comment by vbuchara** [comment] 2024-11-04 13:14
I'm using `Ubuntu 24.04.1 LTS`, and I installed my vscode via the `.deb` file from the vscode site using `apt-get`. Still experiencing the same problems.

I tried to uninstall the extension and install again, to no avail. It seems like the newest vscode update broke the extension. You should look into it.

![Captura de tela de 2024-11-04 09-08-45](https://github.com/user-attachments/assets/91d71266-c7ae-4b95-ae41-12ba0b6a0f53)
![Captura de tela de 2024-11-04 09-09-08](https://github.com/user-attachments/assets/df8f7856-442d-4a04-9981-6e3e26588a10)

**Comment by vbuchara** [comment] 2024-11-04 17:34
> 1. Download the `.deb package`
> 2. And run `sudo apt install ./<file>.deb`
> 
> @vbuchara Is this your way to install vscode? Which .deb do you choose, x64 、Arm32 or Arm64 ?

Amd64. I can say that's it's probably something that vscode changed on 1.95 that is causing the issue. I rolled back to 1.94, and everything is working fine.

**Comment by Zylsjsp** [comment] 2024-11-05 02:29
@shalldie It's not a **distribution-specified** issue, fix on any distribution will benefit all other distributions.
> The extension ruins the whole vscode
As @ZhenyaGoroh indicated, the extension seems corrupted css files. I have a post-install script for my VSCode to substitute VSCode logo in blank page with customized one. It is implemented in Python with built-in `re` module, and works well still in 1.95.x.
You should be able to reproduce the issue through a brand-new installation of linux VSCode, getting this extension clearly uninstalled and removed, then install again.

**Comment by shalldie** [comment] 2024-11-05 03:02
@Zylsjsp It will edit the js file since v2.

It's not always reproducible, at least in my case ...
Some users are also using Ubuntu normally.

I have tried `Ubuntu 24.04.1 LTS (amd6)`,  `Fedora 40 (arm64)` in a vm, and It works fine.
I am still trying =。=

**Comment by shalldie** [comment] 2024-11-05 05:38
又尝试了 `Ubuntu 24.04 LTS (aarch64)` 无果。
感觉可能是我的某个姿势不太对，方便加个Q进一步沟通吗？在你有空的时候  @Zylsjsp

**Comment by vbuchara** [comment] 2024-11-05 11:19
> @Zylsjsp It will edit the js file since v2.
> 
> It's not always reproducible, at least in my case ... Some users are also using Ubuntu normally.
> 
> I have tried `Ubuntu 24.04.1 LTS (amd6)`, `Fedora 40 (arm64)` in a vm, and It works fine. I am still trying =。=

Perhaps it is language dependent? What language are you setting on the vscode? It doesn't help I've never seen an error like this before, so I understand the struggle.

**Comment by shalldie** [comment] 2024-11-05 11:45
> Perhaps it is language dependent? What language are you setting on the vscode? It doesn't help I've never seen an error like this before, so I understand the struggle.

@vbuchara I tried both default English(en) and zh-cn.

![image](https://github.com/user-attachments/assets/7b3ae3ac-b06d-4907-9a55-e7d4482b5ec0)

Two question:
1. Have you ever seen some error or strange msg in `OUTPUT` of `Extension Host`?
2. Once uninstall the extension, vscode restored to normal?

**Comment by vbuchara** [comment] 2024-11-05 11:50
> > Perhaps it is language dependent? What language are you setting on the vscode? It doesn't help I've never seen an error like this before, so I understand the struggle.
> 
> @vbuchara I tried both default English(en) and zh-cn.
> 
> ![image](https://private-user-images.githubusercontent.com/9987486/383131425-7b3ae3ac-b06d-4907-9a55-e7d4482b5ec0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MDc1MzcsIm5iZiI6MTczMDgwNzIzNywicGF0aCI6Ii85OTg3NDg2LzM4MzEzMTQyNS03YjNhZTNhYy1iMDZkLTQ5MDctOWE1NS1lN2Q0NDgyYjVlYzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDVUMTE0NzE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGVmODA5MGI1Y2M4YzE0OTJjODU4NDg1ZGI0YzU0Njg3MDlkNDUxYTczNGU0Nzc1ZTgxMjY4OWVhNjE5MjE0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._Rq_mLA1hJl0rr2zLOtQQ4wzIYq7h4uCs8dReyFcSSE)
> 
> Two question:
> 
> 1. Have you ever seen some error or strange msg in `OUTPUT` of `Extension Host`?
> 2. Once uninstall the extension, vscode restored to normal?
> 
> I don't know if it's related to my use of virtual machines

1. I'm not sure, since it's hard to find the channel with all the text messed up, but I don't think so.
2. If I reinstall vscode and never let the extension do its thing to put the background, the vscode stays normal. It's only when the extension puts the background that the text breaks.

I will see later if something odd appears on the ouput channel.

**Comment by EmmetZ** [comment] 2024-11-05 16:40
- Version: 1.95.1
- Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
- Date: 2024-10-31T05:14:54.222Z
- Electron: 32.2.1
- ElectronBuildId: 10427718
- Chromium: 128.0.6613.186
- Node.js: 20.18.0
- V8: 12.8.374.38-electron.0
- OS: Linux x64 6.11.5-300.fc41.x86_64

I have upgraded my system to Fedora 41, and the bug was fixed, everything seems to work fine ... 🤔

**Comment by vbuchara** [comment] 2024-11-05 19:03
> @shalldie Only thing that caught my eye was this, after I let the extension use sudo to execute the JS to change the background.
> 
> ![Captura de tela de 2024-11-05 13-31-45](https://private-user-images.githubusercontent.com/44072505/383254341-4c658eb5-5c6b-40f5-88a0-60932da6edfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MjgzNTcsIm5iZiI6MTczMDgyODA1NywicGF0aCI6Ii80NDA3MjUwNS8zODMyNTQzNDEtNGM2NThlYjUtNWM2Yi00MGY1LTg4YTAtNjA5MzJkYTZlZGZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDE3MzQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4NDRkMmI2ODliMWE0YzJlYzEyM2ZkMmM4YTI5YjViOTVmMzU5MWQ2ZmQwMzQ3MmQ5NTJhNTM3NjQ0ZmU1Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.N7MdXC_IVZRirj6kt_j5KwokQj9xN8QsIS-tyeFAiVw)

After some digging, this doesn't seem related to the current issue, but you did leave here a piece of throw-able code untreated. It doesn't stop the background from working, but it makes so the "Background has changed!" notification doesn't go through, because the code stopped at the exception.

![image](https://github.com/user-attachments/assets/63af01c7-a502-46c8-a3d0-23c11f0d9512)

**Comment by vbuchara** [comment] 2024-11-05 19:48
As far as I could see, the problem seems to be with the new `workbench.desktop.main.js` generated by the extension, but I'm not sure what exactly. 

I managed to get its contents, copied the portion appended by the extension, pasted on the old `workbench.desktop.main.js` (Before the extension altered it with the `sudoExec(cmdarg, { name: 'Background Extension' })`), and everything seems to be fine.

![image](https://github.com/user-attachments/assets/23ecf6bf-216c-428f-a581-6acdf4d71c67)

**Comment by shalldie** [comment] 2024-11-06 02:28
@vbuchara 
Thanks a lot !
Because I cannot reproduce it here, it is very difficult to find the reason for it.

- New workbench.desktop.main.js generated by the extension, after `sudoExec `
- `I managed to get its contents, copied the portion appended by the extension, pasted on the old workbench.desktop.main.js`

What's the difference between these two files? Or can you send out the file?

**Comment by abbytec** [comment] 2024-11-06 16:03
Same problem here, all the buttons on vscode seem to be text-corrupted until I reinstall vscode.
- Ubuntu 24.04.1 LTS
- kernel Linux 6.8.0-48-generic
- Vscode version: code_1.95.1-1730355339_amd64.deb
- OS language: es-ES
- Vscode display language: (es)
The issue happens after I give sudo permissions on:
![image](https://github.com/user-attachments/assets/a316c682-e6fd-49a4-8756-d90ad2d9638f)

**Comment by vbuchara** [comment] 2024-11-06 20:45
> @vbuchara Thanks a lot ! Because I cannot reproduce it here, it is very difficult to find the reason for it.
> 
> * New workbench.desktop.main.js generated by the extension, after `sudoExec `
> * `I managed to get its contents, copied the portion appended by the extension, pasted on the old workbench.desktop.main.js`
> 
> What's the difference between these two files? Or can you send out the file?

I don't know, I skimmed over both files, I didn't spot a huge difference. It doesn't help it's a big minified file, so it's hard to spot anything. 

I can also say that this diference is weird, since your code just reads from the original file and adds to it. Maybe try to use fs or some other command to append to it? Instead of reading the contents and creating a new file.

**Comment by Leroymilo** [comment] 2024-11-07 10:57
Same problem on Nobara 40 (modified version of Fedora). It only happens on version 1.95.0 and later of VSCode, version 1.94.2 is ok.
I didn't see anyone sharing this warning message, I get it every time I start VSCode after activating the extension with sudo/admin:
![Screenshot_20241107_193346](https://github.com/user-attachments/assets/86f43492-5e48-4d17-883a-0bcdeb10f36f)

**Comment by KaiDaCanadian** [comment] 2024-11-08 20:26
> Same problem on Nobara 40 (modified version of Fedora). It only happens on version 1.95.0 and later of VSCode, version 1.94.2 is ok. I didn't see anyone sharing this warning message, I get it every time I start VSCode after activating the extension with sudo/admin: ![Screenshot_20241107_193346](https://private-user-images.githubusercontent.com/88249282/383927487-86f43492-5e48-4d17-883a-0bcdeb10f36f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwOTc0MTQsIm5iZiI6MTczMTA5NzExNCwicGF0aCI6Ii84ODI0OTI4Mi8zODM5Mjc0ODctODZmNDM0OTItNWU0OC00ZDE3LTg4M2EtMGJjZGViMTBmMzZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDIwMTgzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMjVhYTA2MzI0YTAxNTYxOWZjMDQxMzY3ZTY4OWRmODNmNjU2ZWIxZjcxMjU4YTljNDlhZmI2ODhkOWE3ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Cx9pyflBNX3_Ud_9PNQCuNTVr06FLzKujRycGllyJZ4)

This is just the "Your VSCode installation is corrupt" message but with screwed up localization

**Comment by shalldie** [comment] 2024-11-09 05:48
#### Those friends who have problems, add a emoji to tell me if your scene is like this?

1. vscode + background, works well.
2. vscode upgrade，through the package manager, it is not the update of VSCode itself
3. problems occur.
4. If the vscode directory is not deleted in the future, reinstallation will still encounter problems

#### 出现该问题的朋友，点个 emoji 来告诉我你是否是这种场景？

1. vscode + background, 用的挺好的.
2. 通过包管理器更新vscode，而不是自身的“更新”功能
3. 出现问题
4. 后续如果始终直接用包管理器重装（没有先remove），问题始终存在。

---

#### Temporary repair - 临时修复

- Delete the vscode directory(`/usr/share/code`、`/opt/visual-studio-code`),  then install again.
- I will fix this issue as soon as possible before the next vscode update

- 删除vscode目录(`/usr/share/code`、`/opt/visual-studio-code`), 重装。
- 我会尽快修复这个问题

**Comment by shalldie** [comment] 2024-11-09 09:09
Fixed in `v2.0.2`

**Closed by shalldie** 2024-11-09 09:09 UTC
Labels: bug, help wanted
