### ISSUE TITLE
Make Background Take Up Entire VSC

### ISSUE THREAD

**Issue by AndrewFirePvP7** [shalldie/vscode-background#294] opened 2022-06-09 02:06 UTC
There's no setting to make the background take up ALL of Visual Studio Code. It only takes up the background of just the code. I want it to take up EVERYTHING. I outlined in red where I want the image to fill in additionally to where it's already at. How can I do this?
![VSC_Background-Idea](https://user-images.githubusercontent.com/29314485/172748665-d308010a-6154-489b-9a50-04bb05b3f816.png)
.

**Comment by frg2089** [comment] 2022-06-10 03:44
This extension are not supported to set background for full view.

[manasxx.background-cover](https://github.com/AShujiao/vscode-background-cover) may be helpful to you. 

Duplicate of #189 (Chinese), #267 (Chinese), #268 (Chinese), #288 (Chinese)

**Comment by AndrewFirePvP7** [comment] 2022-06-10 15:50
Thank you!

**Closed** 2022-06-10 15:50 UTC
